stages:
  - build
  - deploy

variables:
  TSFILE: "tailscale_1.28.0_amd64.tgz"

before_script:
  # Install required dependencies
  - apt-get update -qq && apt-get install -y iptables wget curl

  # Install Node.js and npm
  - curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
  - apt-get install -y nodejs

  # Install Tailscale
  - cd /usr/local/bin
  - wget https://pkgs.tailscale.com/stable/${TSFILE} -P /tmp
  - tar xzf /tmp/${TSFILE} --strip-components=1
  - rm /tmp/${TSFILE}

  # Configure and start Tailscale
  - mkdir -p /var/run/tailscale
  - update-alternatives --set iptables /usr/sbin/iptables-legacy
  - tailscaled --state="mem:" &
  - sleep 3 # Give tailscaled time to start
  - tailscale up --authkey=${TAILSCALE_AUTHKEY} --hostname="gitlab-$(cat /etc/hostname)"
  - tailscale status

build:
  stage: build
  script:
    - cd $CI_PROJECT_DIR
    - npm ci # Clean install of dependencies
    - npm run lint # Run ESLint
    - npm run build # Build the project
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  artifacts:
    paths:
      - .next/ # Save build artifacts
    expire_in: 4 days # Keep artifacts for a week
    when: always # Save artifacts even if the build fails

deploy:
  stage: deploy
  script: |
    echo "Login to machine was successful"
    ssh -o "StrictHostKeyChecking no" ubuntu@sora "
    cd ~/server/oas-next && sh .scripts/live.sh
    "
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success # Only deploy if previous stages succeed
