services:
  oas-next:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bun-oas-next
    environment:
      - NODE_ENV=PRODUCTION
    restart: unless-stopped
    networks:
      - oas
      - npm-network
    volumes:
      - ./data:/app/data

networks:
  oas:
    external: true
  npm-network:
    external: true
