services:
  oas-next:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oas-next
    environment:
      - NODE_ENV=PRODUCTION
    ports:
      - "127.0.0.1:6800:3000"
      - "[::1]:6800:3000"
    restart: unless-stopped
    networks:
      - oas

networks:
  oas:
    external: true
